// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_mvSw2Uk_uoknotYwGi06eIeiGQqKoPI',
    appId: '1:1077441480461:web:9a5759b6110a15651c5244',
    messagingSenderId: '1077441480461',
    projectId: 'petbridge-3acc9',
    authDomain: 'petbridge-3acc9.firebaseapp.com',
    storageBucket: 'petbridge-3acc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4fJvPrCyMgigKqk3bNRvuDkVqr-n3nZQ',
    appId: '1:1077441480461:android:6b93f80fa4d8a1201c5244',
    messagingSenderId: '1077441480461',
    projectId: 'petbridge-3acc9',
    storageBucket: 'petbridge-3acc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVmSZrP9h2TwdaQkcizDlKV5pKFpfN_zo',
    appId: '1:1077441480461:ios:9a26927b6bd71a331c5244',
    messagingSenderId: '1077441480461',
    projectId: 'petbridge-3acc9',
    storageBucket: 'petbridge-3acc9.firebasestorage.app',
    iosBundleId: 'com.example.petbridgeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVmSZrP9h2TwdaQkcizDlKV5pKFpfN_zo',
    appId: '1:1077441480461:ios:9a26927b6bd71a331c5244',
    messagingSenderId: '1077441480461',
    projectId: 'petbridge-3acc9',
    storageBucket: 'petbridge-3acc9.firebasestorage.app',
    iosBundleId: 'com.example.petbridgeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_mvSw2Uk_uoknotYwGi06eIeiGQqKoPI',
    appId: '1:1077441480461:web:7b63b0377e33b1651c5244',
    messagingSenderId: '1077441480461',
    projectId: 'petbridge-3acc9',
    authDomain: 'petbridge-3acc9.firebaseapp.com',
    storageBucket: 'petbridge-3acc9.firebasestorage.app',
  );
}
